name: featurebase_dart
description: "A Dart SDK for Featurebase"
version: 0.0.4
homepage: https://pub.dev/packages/featurebase

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  source_gen: ^1.5.0
  json_serializable: ^6.8.0

flutter:

targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            "^lib/{{}}.dart": "lib/src/generated/{{}}.g.dart"
      freezed:
        options:
          build_extensions:
            "^lib/{{}}.dart": "lib/src/generated/{{}}.freezed.dart"
